#!/bin/bash

for item in $(ls)
do
    if [[ -d "${item}" && ! -L "${item}" ]]; then
        cd $item
        echo $item
        ../../bin/ratom.x atom.inp > solution.dat

#  The tool cmp compares bytes.
#  There are some differences comparing non-integer values
#
#        cmp solution.dat solution.dat.ref
#        if [ $? -eq 0 ]; then
#            echo $item OK
#        else
#            echo $item FAILED
#        fi
        cd ..
    fi
done
